name: Mizugaki-Install-Dependencies
description: Install dependencies for Mizugaki

inputs:
  checkout:
    description: Skip checkout if false
    default: true
  path:
    description: Relative path under $GITHUB_WORKSPACE to place the repository
    default: build-deps
  cmake_build_option:
    type: string
    default: ''

runs:
  using: "composite"

  steps:
    - name: Checkout_Takatori
      uses: actions/checkout@v4
      if: ${{ inputs.checkout == 'true' }}
      with:
        repository: project-tsurugi/takatori
        path: ${{ inputs.path }}/takatori
        ref: master

    - name: Checkout_Yugawara
      if: ${{ inputs.checkout == 'true' }}
      uses: actions/checkout@v4
      with:
        repository: project-tsurugi/yugawara
        path: ${{ inputs.path }}/yugawara
        ref: master
        submodules: true

    - name: Install_Takatori
      run: |
        cd ${{ inputs.path }}/takatori
        rm -fr build
        mkdir build
        cd build
        cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DBUILD_TESTS=OFF -DBUILD_DOCUMENTS=OFF -DBUILD_STRICT=OFF -DCMAKE_INSTALL_PREFIX=${GITHUB_WORKSPACE}/.local ${{ inputs.cmake_build_option }} ..
        cmake --build . --target install --clean-first
      shell: bash

    - name: Install_hopscotch-map
      run: |
        cd ${{ inputs.path }}/yugawara/third_party/hopscotch-map
        rm -fr ../../build-hopscotch-map
        mkdir ../../build-hopscotch-map
        cd ../../build-hopscotch-map
        cmake -G Ninja -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_INSTALL_PREFIX=${GITHUB_WORKSPACE}/.local ${{ inputs.cmake_build_option }} ../third_party/hopscotch-map
        cmake --build . --target install
      shell: bash

    - name: Install_Yugawara
      run: |
        cd ${{ inputs.path }}/yugawara
        rm -fr build
        mkdir build
        cd build
        cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DBUILD_TESTS=OFF -DBUILD_DOCUMENTS=OFF -DBUILD_STRICT=OFF -DCMAKE_INSTALL_PREFIX=${GITHUB_WORKSPACE}/.local ${{ inputs.cmake_build_option }} ..
        cmake --build . --target install --clean-first
      shell: bash
